### ISSUE TITLE
[APP] Tablet Version

### ISSUE THREAD

**Issue by joofio** [Gravitate-Health/end-user-app-WP4#1]
Tablet Version of the app

**Comment by joofio** [comment]
The app for tablet is a different one from the current mobile phone one? 

meaning: the developments done in one should replicated in the other or once will be enough?

**Comment by Capa00** [comment]
The app will be responsive so the code developed will be one and there will be no need to create a new app for tablets

**Comment by joofio** [comment]
steps:
1. mockup

3. development (10-12 )

**Comment by joofio** [comment]
postponed by italian video

**Comment by joofio** [comment]
@riccardo-leoni-dw  done right?
