### ISSUE TITLE
[RMM] Being able to browse "tailored" RMM content in the app frontend

### ISSUE THREAD

**Issue by joofio** [Gravitate-Health/end-user-app-WP4#11]

**Comment by joofio** [comment]
depends on having a service with data: https://github.com/Gravitate-Health/mvp-issues/issues/10

**Comment by riccardo-leoni-dw** [comment]
For the first MS (09/05) we will follow the mockups in issue #20 , in particular we'll:

- change the current ‘medication details’ section
- create the 'support material' section accessible from the 'medication details' section
- modify the leaflet section by removing the two tabs and creating a separate ‘focused leaflet’ section
- test the development environment
- initiate developing the ‘summary lens’ section

After this first phase, we can start integrating the services that will be ready to be tested.

**Comment by joofio** [comment]
Issues:

#29  -> change the current ‘medication details’ section
this one - >  create the 'support material' section accessible from the 'medication details' section
#29  -> modify the leaflet section by removing the two tabs and creating a separate ‘focused leaflet’ section
no issue -> test the development environment
#27  -> initiate developing the ‘summary lens’ section

**Comment by joofio** [comment]
Test and close

**Comment by joofio** [comment]
reduce the size on the bubbles/ font on the screen, is it possible? Or change to drop down/other format.

The rest seems ok.
@riccardo-leoni-dw 

![image](https://github.com/user-attachments/assets/3f83b9e3-7364-40b3-8c9a-4422d4c3a990)

**Comment by joofio** [comment]
Done in mvp app for prod October 2024
