### ISSUE TITLE
[APP] Text-to-speech

### ISSUE THREAD

**Issue by joofio** [Gravitate-Health/end-user-app-WP4#2]
Notes on this:

The scope is "only" to get information in a speech format. We decided not to incorporate interaction / conversation since it would increate development time considerably.

**Comment by RiccardoLeoni** [comment]
we will develop "text to speech" functionality using native system readers, Talkback for Android and Voiceover for iOS

**Comment by joofio** [comment]
@riccardo-leoni-dw check if processing is done on device or cloud

**Comment by joofio** [comment]
@riccardo-leoni-dw  done right?
